# Generated by Django 5.0.1 on 2024-01-08 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(limit_value=11)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(limit_value=11)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(limit_value=5)]),
        ),
    ]
